### ISSUE TITLE
你好，我最近用那个globalplanner的dijkstra，会得到currentEnd_和nextEnd_都为0然后退出

### ISSUE THREAD

**Issue by pengjiawei** [zkytony/ROSNavigationGuide#2]
我的起始点和结束点的像素表示是(9.5,9.5)到(19.5,19.5)然后我放了一个lethal_obstacle在(15,15)但是路径就规划不出来了，谢谢~我不太明白那个dijkstra算法是怎么样一个计算流程

**Comment by zkytony** [comment]
你可以看ros [navigation](https://github.com/ros-planning/navigation)的源代码去了解dijkstra是怎么实现的。你的地图有多大？不放lethal obstacle行不行？

建议你去ROS 论坛 (ROS Ask) 上提问，我最近没有接触ros navigation。我没有手动添加过lethal obstacle。我一般用Blender建立一个虚拟环境，让机器人在其中navigate。
